batch_size: 64
epochs: 100
eval_every_n_epochs: 1
#fine_tune_from: ./training_results/pretraining
fine_tune_from: /home/tfu24/main/runs_multiview/Oct19_08-29-19/checkpoints
# fine_tune_from: scratch
log_every_n_steps: 50
gpu: cuda:0
random_seed: 3
task: regression

optim:
  optimizer: Adam
  lr: 0.005
  momentum: 0.9
  weight_decay: 1e-6

model: 
  atom_fea_len: 64
  h_fea_len: 512
  n_conv: 3
  n_h: 1

data_name: 'QMOF'
# data_name: 'hMOF_CO2_0.5'

dataset:
  # root_dir: ./hMOF_cif
#  # label_dir: ./benchmark_datasets/hMOF/graph/large/hMOF_CO2_0.5_large_graph.csv
  root_dir: /home/tfu24/main/benchmark_datasets/jdft2d/graph
#  root_dir: /home/tfu24/main/benchmark_datasets/phonos/graph
#  root_dir: /home/tfu24/main/benchmark_datasets/kvrh/graph
#  root_dir: /home/tfu24/main/benchmark_datasets/gvrh/graph
#  root_dir: /home/tfu24/main/benchmark_datasets/band_gap
  label_dir: /home/tfu24/main/benchmark_datasets/jdft2d/graph/id_prop.csv
#  label_dir: /home/tfu24/main/benchmark_datasets/phonos/graph/id_prop.csv
#  label_dir: /home/tfu24/main/benchmark_datasets/kvrh/graph/id_prop_100.csv
#  label_dir: /home/tfu24/main/benchmark_datasets/gvrh/graph/id_prop.csv
#  label_dir: /home/tfu24/main/benchmark_datasets/band_gap/id_prop.csv

  max_num_nbr: 12
  radius: 8
  dmin: 0
  step: 0.2


dataloader:
  val_ratio: 0.15
  test_ratio: 0.15
  num_workers: 0


